# Generated by Django 5.2.7 on 2025-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.CharField(blank=True, choices=[('PERDA_GORDURA', 'Perda de Gordura'), ('GANHO_MASSA', 'Ganho de Massa Muscular'), ('QUALIDADE_VIDA', 'Qualidade de Vida e Saúde'), ('OUTRO', 'Outro')], db_index=True, max_length=50, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial')], db_index=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
