# Generated by Django 5.2.7 on 2025-11-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='gender',
        ),
    ]
