# Generated by Django 5.2.7 on 2025-12-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
