# Generated by Django 5.2.7 on 2025-12-22 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='target_body_fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de gordura corporal alvo', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso alvo do paciente em kg', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='PatientDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('photo', 'Foto'), ('text', 'Texto'), ('meal', 'Refeição'), ('exercise', 'Exercício'), ('weight', 'Peso'), ('note', 'Observação')], max_length=20, verbose_name='Tipo de Entrada')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_diary_photos/', verbose_name='Foto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='patients.patientprofile', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Entrada no Diário',
                'verbose_name_plural': 'Entradas no Diário',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='patients.patientdiaryentry', verbose_name='Entrada do Diário')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdherenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data da medição de adesão', verbose_name='Data')),
                ('adherence_rate', models.DecimalField(decimal_places=2, help_text='Taxa de adesão em porcentagem (0.00 a 100.00)', max_digits=5, verbose_name='Taxa de Adesão')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_records', to='patients.patientprofile', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro de Adesão',
                'verbose_name_plural': 'Registros de Adesão',
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SocialLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='patients.patientdiaryentry', verbose_name='Entrada do Diário')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Curtida',
                'verbose_name_plural': 'Curtidas',
                'unique_together': {('user', 'diary_entry')},
            },
        ),
    ]
