# Generated by Django 5.2.7 on 2026-01-06 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_type'),
        ('diets', '0008_defaultpreset_and_more'),
        ('patients', '0004_patientprofile_target_body_fat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_confirmations', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'appointment_confirmations',
            },
        ),
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('arms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('legs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('glutes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'body_measurements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.CharField(choices=[('front', 'Frente'), ('side', 'Lado'), ('back', 'Costas')], max_length=10)),
                ('photo', models.ImageField(upload_to='progress_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'progress_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MealCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='diets.meal')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_checkins', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'meal_checkins',
                'ordering': ['-checked_in_at'],
                'unique_together': {('patient', 'meal', 'checked_in_at')},
            },
        ),
        migrations.CreateModel(
            name='PatientMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories_consumed', models.IntegerField(default=0)),
                ('calories_goal', models.IntegerField(default=2000)),
                ('water_consumed', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('water_goal', models.DecimalField(decimal_places=2, default=2.5, max_digits=4)),
                ('focus_score', models.IntegerField(default=0)),
                ('focus_goal', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'patient_metrics',
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
