# Generated by Django 5.2.7 on 2026-01-10 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_appointmentconfirmation_bodymeasurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('PERDA_PESO', 'Perda de peso - Redução de peso com foco em saúde e sustentabilidade'), ('GANHO_MUSCULAR', 'Ganho de massa muscular - Hipertrofia e desenvolvimento muscular'), ('MANUTENCAO_PESO', 'Manutenção do peso - Equilíbrio e manutenção do peso atual'), ('PERFORMANCE_ESPORTIVA', 'Performance esportiva - Otimização do desempenho atlético e competitivo'), ('GESTACAO_LACTACAO', 'Gestação e lactação - Acompanhamento nutricional materno-infantil'), ('DOENCAS_CRONICAS', 'Manejo de doenças crônicas - Diabetes, hipertensão, dislipidemias, doenças cardiovasculares'), ('REABILITACAO_NUTRICIONAL', 'Reabilitação nutricional - Recuperação pós-cirúrgica ou pós-doença'), ('TRANSTORNOS_ALIMENTARES', 'Transtornos alimentares - Apoio no tratamento de anorexia, bulimia, compulsão alimentar'), ('ALERGIAS_INTOLERANCIAS', 'Alergias e intolerâncias alimentares - Manejo de restrições alimentares específicas'), ('DISTURBIOS_GASTROINTESTINAIS', 'Distúrbios gastrointestinais - Síndrome do intestino irritável, doença celíaca, refluxo'), ('CONDICOES_HORMONAIS', 'Condições hormonais - SOP (Síndrome dos Ovários Policísticos), hipotireoidismo, menopausa'), ('NUTRICAO_FUNCIONAL', 'Nutrição funcional e integrativa - Abordagem holística e preventiva'), ('SUPLEMENTACAO_ORIENTADA', 'Suplementação orientada - Otimização do uso de suplementos nutricionais'), ('SAUDE_IDOSO', 'Saúde do idoso - Nutrição voltada para longevidade e qualidade de vida'), ('PREVENCAO_DOENCAS', 'Prevenção de doenças - Promoção de saúde e hábitos preventivos')], db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'clinical_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
