# Generated by Django 5.2.7 on 2026-01-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patientprofile_goal_clinicalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
