# Generated by Django 5.2.7 on 2026-01-19 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0011_alter_defaultpreset_diet_type_and_more'),
        ('patients', '0007_clinicalnote_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='meal_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='diets.meal')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_photos', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'meal_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
