# Generated by Django 5.2.7 on 2025-12-06 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diets', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diets', to='patients.patientprofile'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='taco_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_items', to='diets.alimentotaco'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='tbca_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_items', to='diets.alimentotbca'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='usda_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_items', to='diets.alimentousda'),
        ),
        migrations.AddField(
            model_name='meal',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='diets.diet'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diets.meal'),
        ),
    ]
