# Generated by Django 5.2.7 on 2025-11-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plano Alimentar', 'verbose_name_plural': 'Planos Alimentares'},
        ),
        migrations.AddField(
            model_name='diet',
            name='formula_tmb',
            field=models.CharField(blank=True, choices=[('harris-benedict', 'Harris-Benedict'), ('mifflin-st-jeor', 'Mifflin-St Jeor'), ('katch-mcardle', 'Katch-McArdle')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='gcdt_calculado',
            field=models.PositiveIntegerField(blank=True, help_text='Gasto Calórico Diário Total calculado', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se o plano está ativo'),
        ),
        migrations.AddField(
            model_name='diet',
            name='meta_calorias',
            field=models.PositiveIntegerField(blank=True, help_text='Meta de calorias diárias', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='meta_carboidratos',
            field=models.PositiveIntegerField(blank=True, help_text='Meta de carboidratos em gramas', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='meta_gorduras',
            field=models.PositiveIntegerField(blank=True, help_text='Meta de gorduras em gramas', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='meta_proteinas',
            field=models.PositiveIntegerField(blank=True, help_text='Meta de proteínas em gramas', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='nivel_atividade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fator de atividade física', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('manter', 'Manter peso'), ('perder', 'Perder peso'), ('ganhar', 'Ganhar peso')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='tmb_calculado',
            field=models.PositiveIntegerField(blank=True, help_text='Taxa Metabólica Basal calculada', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
