# Generated by Django 5.2.7 on 2025-12-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='taco_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='diets.alimentotaco'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='tbca_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='diets.alimentotbca'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='usda_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='diets.alimentousda'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_rel', to='diets.diet'),
        ),
    ]
