# Generated by Django 5.2.7 on 2025-12-15 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_alter_fooditem_taco_food_alter_fooditem_tbca_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaCaseira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da medida caseira (ex: Colher de sopa)', max_length=100, unique=True)),
                ('peso_medio_g', models.FloatField(blank=True, help_text='Peso médio em gramas', null=True)),
                ('categoria', models.CharField(choices=[('utensiilio', 'Utensílio de cozinha'), ('porcao', 'Porção/Quantidade'), ('unidade', 'Unidade natural'), ('embalagem', 'Embalagem'), ('liquido', 'Medida de líquido'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('quantidade_amostras', models.IntegerField(default=0, help_text='Número de amostras usadas para calcular a média')),
                ('eh_liquido', models.BooleanField(default=False, help_text='Se a medida é tipicamente para líquidos')),
                ('volume_ml', models.FloatField(blank=True, help_text='Volume em ml (para líquidos)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medida Caseira',
                'verbose_name_plural': 'Medidas Caseiras',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='diets_medid_nome_cd56e8_idx'), models.Index(fields=['categoria'], name='diets_medid_categor_957ecc_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlimentoMedidaIBGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.CharField(help_text='Código do alimento no IBGE', max_length=10)),
                ('nome_alimento', models.CharField(help_text='Nome do alimento', max_length=200)),
                ('preparacao', models.CharField(choices=[('cru', 'Cru(a)'), ('cozido', 'Cozido(a)'), ('frito', 'Frito(a)'), ('assado', 'Assado(a)'), ('grelhado', 'Grelhado(a)/brasa/churrasco'), ('refogado', 'Refogado(a)'), ('empanado', 'Empanado(a)/à milanesa'), ('molho_vermelho', 'Molho vermelho'), ('molho_branco', 'Molho branco'), ('ensopado', 'Ensopado'), ('sopa', 'Sopa'), ('vinagrete', 'Ao vinagrete'), ('manteiga', 'Com manteiga/óleo'), ('alho_oleo', 'Ao alho e óleo'), ('mingau', 'Mingau'), ('nao_aplica', 'Não se aplica')], default='nao_aplica', max_length=20)),
                ('peso_g', models.FloatField(help_text='Peso em gramas para esta medida específica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taco_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_ibge', to='diets.alimentotaco')),
                ('tbca_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_ibge', to='diets.alimentotbca')),
                ('usda_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas_ibge', to='diets.alimentousda')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='diets.medidacaseira')),
            ],
            options={
                'verbose_name': 'Medida de Alimento IBGE',
                'verbose_name_plural': 'Medidas de Alimentos IBGE',
                'ordering': ['nome_alimento', 'medida__nome'],
                'indexes': [models.Index(fields=['nome_alimento'], name='diets_alime_nome_al_9bafa1_idx'), models.Index(fields=['codigo_ibge'], name='diets_alime_codigo__a0bddd_idx'), models.Index(fields=['preparacao'], name='diets_alime_prepara_9d9606_idx')],
                'unique_together': {('codigo_ibge', 'medida', 'preparacao')},
            },
        ),
    ]
