# Generated by Django 5.2.7 on 2025-11-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_alter_diet_options_diet_formula_tmb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoTACO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do alimento na TACO', max_length=10, unique=True)),
                ('nome', models.CharField(help_text='Nome do alimento', max_length=200)),
                ('energia_kcal', models.FloatField(help_text='Energia em kcal por 100g')),
                ('proteina_g', models.FloatField(help_text='Proteína em gramas por 100g')),
                ('lipidios_g', models.FloatField(help_text='Lipídios em gramas por 100g')),
                ('carboidrato_g', models.FloatField(help_text='Carboidrato em gramas por 100g')),
                ('fibra_g', models.FloatField(default=0, help_text='Fibra em gramas por 100g')),
                ('calcio_mg', models.FloatField(blank=True, help_text='Cálcio em mg por 100g', null=True)),
                ('ferro_mg', models.FloatField(blank=True, help_text='Ferro em mg por 100g', null=True)),
                ('sodio_mg', models.FloatField(blank=True, help_text='Sódio em mg por 100g', null=True)),
                ('vitamina_c_mg', models.FloatField(blank=True, help_text='Vitamina C em mg por 100g', null=True)),
                ('grupo', models.CharField(help_text='Grupo alimentar (ex: Cereais, Carnes, etc.)', max_length=50)),
                ('unidade_caseira', models.CharField(blank=True, help_text='Unidade caseira (ex: 1 xícara, 1 fatia)', max_length=50, null=True)),
                ('peso_unidade_caseira_g', models.FloatField(blank=True, help_text='Peso em gramas da unidade caseira', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alimento TACO',
                'verbose_name_plural': 'Alimentos TACO',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='diets_alime_nome_32bfcb_idx'), models.Index(fields=['grupo'], name='diets_alime_grupo_af70ea_idx')],
            },
        ),
    ]
