# Generated by Django 5.2.7 on 2025-11-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_alimentotaco'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
