# Generated by Django 5.2.7 on 2025-12-16 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_medidacaseira_alimentomedidaibge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_source', models.CharField(max_length=50)),
                ('food_id', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'food_name'], name='diets_favor_user_id_b260d8_idx')],
                'unique_together': {('user', 'food_source', 'food_id')},
            },
        ),
    ]
