# Generated by Django 5.2.7 on 2025-12-22 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_favoritefood'),
        ('patients', '0004_patientprofile_target_body_fat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='diets.diet')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_view_logs', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Log de Visualização de Dieta',
                'verbose_name_plural': 'Logs de Visualização de Dieta',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['patient', 'viewed_at'], name='diets_dietv_patient_a6da31_idx'), models.Index(fields=['diet'], name='diets_dietv_diet_id_346111_idx')],
            },
        ),
    ]
