# Generated by Django 5.2.7 on 2025-11-25 02:53

import diets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_diet_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Se o plano está ativo'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='meals',
            field=models.JSONField(validators=[diets.models.validate_meals_schema]),
        ),
        migrations.AlterField(
            model_name='diet',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='diet',
            name='substitutions',
            field=models.JSONField(blank=True, null=True, validators=[diets.models.validate_substitutions_schema]),
        ),
        migrations.CreateModel(
            name='AlimentoCustomizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Alimento')),
                ('categoria', models.CharField(default='Outros', max_length=100, verbose_name='Categoria')),
                ('energia_kcal', models.FloatField(default=0, verbose_name='Energia (kcal)')),
                ('proteina_g', models.FloatField(default=0, verbose_name='Proteínas (g)')),
                ('carboidrato_g', models.FloatField(default=0, verbose_name='Carboidratos (g)')),
                ('lipidios_g', models.FloatField(default=0, verbose_name='Lipídios (g)')),
                ('fibra_g', models.FloatField(default=0, verbose_name='Fibras (g)')),
                ('sodio_mg', models.FloatField(default=0, verbose_name='Sódio (mg)')),
                ('ferro_mg', models.FloatField(default=0, verbose_name='Ferro (mg)')),
                ('calcio_mg', models.FloatField(default=0, verbose_name='Cálcio (mg)')),
                ('vitamina_c_mg', models.FloatField(default=0, verbose_name='Vitamina C (mg)')),
                ('porcao', models.FloatField(default=100, verbose_name='Porção padrão')),
                ('unidade', models.CharField(default='g', max_length=10, verbose_name='Unidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_customizados', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista')),
            ],
            options={
                'verbose_name': 'Alimento Customizado',
                'verbose_name_plural': 'Alimentos Customizados',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nutritionist', 'nome'], name='diets_alime_nutriti_c480f3_idx'), models.Index(fields=['nutritionist', 'categoria'], name='diets_alime_nutriti_0d7632_idx')],
            },
        ),
    ]
