# Generated by Django 5.2.7 on 2025-11-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0006_alter_diet_is_active_alter_diet_meals_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlimentoCustomizado',
        ),
    ]
