# Generated by Django 5.2.7 on 2025-11-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0007_delete_alimentocustomizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoTBCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do alimento na TBCA', max_length=20, unique=True)),
                ('nome', models.CharField(help_text='Nome do alimento', max_length=255)),
                ('energia_kcal', models.FloatField(help_text='Energia em kcal por 100g')),
                ('proteina_g', models.FloatField(help_text='Proteína em gramas por 100g')),
                ('lipidios_g', models.FloatField(help_text='Lipídios em gramas por 100g')),
                ('carboidrato_g', models.FloatField(help_text='Carboidrato em gramas por 100g')),
                ('fibra_g', models.FloatField(blank=True, help_text='Fibra em gramas por 100g', null=True)),
                ('sodio_mg', models.FloatField(blank=True, help_text='Sódio em mg por 100g', null=True)),
                ('ferro_mg', models.FloatField(blank=True, help_text='Ferro em mg por 100g', null=True)),
                ('calcio_mg', models.FloatField(blank=True, help_text='Cálcio em mg por 100g', null=True)),
                ('vitamina_c_mg', models.FloatField(blank=True, help_text='Vitamina C em mg por 100g', null=True)),
                ('vitamina_a_mcg', models.FloatField(blank=True, help_text='Vitamina A em mcg por 100g', null=True)),
                ('grupo', models.CharField(help_text='Grupo alimentar', max_length=100)),
                ('unidade_caseira', models.CharField(blank=True, help_text='Unidade caseira', max_length=50, null=True)),
                ('peso_unidade_caseira_g', models.FloatField(blank=True, help_text='Peso em gramas da unidade caseira', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alimento TBCA',
                'verbose_name_plural': 'Alimentos TBCA',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='diets_alime_nome_c11e58_idx'), models.Index(fields=['grupo'], name='diets_alime_grupo_8e2e43_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlimentoUSDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.IntegerField(help_text='FDC ID do USDA', unique=True)),
                ('nome', models.CharField(help_text='Nome do alimento', max_length=255)),
                ('energia_kcal', models.FloatField(help_text='Energia em kcal por 100g')),
                ('proteina_g', models.FloatField(help_text='Proteína em gramas por 100g')),
                ('lipidios_g', models.FloatField(help_text='Lipídios em gramas por 100g')),
                ('carboidrato_g', models.FloatField(help_text='Carboidrato em gramas por 100g')),
                ('fibra_g', models.FloatField(blank=True, help_text='Fibra em gramas por 100g', null=True)),
                ('sodio_mg', models.FloatField(blank=True, help_text='Sódio em mg por 100g', null=True)),
                ('ferro_mg', models.FloatField(blank=True, help_text='Ferro em mg por 100g', null=True)),
                ('calcio_mg', models.FloatField(blank=True, help_text='Cálcio em mg por 100g', null=True)),
                ('vitamina_c_mg', models.FloatField(blank=True, help_text='Vitamina C em mg por 100g', null=True)),
                ('vitamina_a_mcg', models.FloatField(blank=True, help_text='Vitamina A em mcg por 100g', null=True)),
                ('vitamina_d_mcg', models.FloatField(blank=True, help_text='Vitamina D em mcg por 100g', null=True)),
                ('categoria', models.CharField(help_text='Categoria USDA', max_length=100)),
                ('porcao_padrao_g', models.FloatField(default=100, help_text='Porção padrão em gramas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alimento USDA',
                'verbose_name_plural': 'Alimentos USDA',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='diets_alime_nome_7f309e_idx'), models.Index(fields=['categoria'], name='diets_alime_categor_fe0db0_idx')],
            },
        ),
    ]
