# Generated by Django 5.2.7 on 2026-01-03 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0007_merge_20260102_2014'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('cafe_da_manha', 'Café da Manhã'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('lanche_manha', 'Lanche da Manhã'), ('lanche_tarde', 'Lanche da Tarde'), ('ceia', 'Ceia'), ('suplemento', 'Suplemento')], help_text='Tipo de refeição para este preset padrão', max_length=20)),
                ('diet_type', models.CharField(choices=[('balanced', 'Balanceado'), ('lowcarb', 'Low Carb'), ('highcarb', 'High Carb'), ('ketogenic', 'Cetogênico'), ('vegetarian', 'Vegetariano'), ('vegan', 'Vegano'), ('hypertrophy', 'Hipertrofia'), ('weight_loss', 'Perda de Peso'), ('weight_gain', 'Ganho de Peso'), ('custom', 'Personalizado')], help_text='Tipo de dieta para este preset padrão', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Se o preset padrão está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preset Padrão',
                'verbose_name_plural': 'Presets Padrão',
                'ordering': ['nutritionist', 'meal_type', 'diet_type'],
            },
        ),
        migrations.RenameIndex(
            model_name='mealpreset',
            new_name='diets_mealp_nutriti_c4b3fd_idx',
            old_name='diets_mealpre_nutrit_7d0b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='mealpreset',
            new_name='diets_mealp_nutriti_e8e62b_idx',
            old_name='diets_mealpre_nutrit_8f1d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='mealpreset',
            new_name='diets_mealp_meal_ty_037e22_idx',
            old_name='diets_mealpre_meal_t_8f1d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='mealpreset',
            new_name='diets_mealp_is_acti_d6e86d_idx',
            old_name='diets_mealpre_is_act_8f1d2a_idx',
        ),
        migrations.AddField(
            model_name='defaultpreset',
            name='nutritionist',
            field=models.ForeignKey(help_text='Nutricionista proprietário do preset padrão', on_delete=django.db.models.deletion.CASCADE, related_name='default_presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaultpreset',
            name='preset',
            field=models.ForeignKey(help_text='Preset selecionado como padrão', on_delete=django.db.models.deletion.CASCADE, to='diets.mealpreset'),
        ),
        migrations.AlterUniqueTogether(
            name='defaultpreset',
            unique_together={('nutritionist', 'meal_type', 'diet_type')},
        ),
    ]
