# Generated by Django 5.2.7 on 2025-11-28 18:12

import diets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_alimentotbca_alimentousda'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='calculation_method',
            field=models.CharField(default='mifflin', help_text='Método de cálculo (mifflin, harris, etc)', max_length=50),
        ),
        migrations.AddField(
            model_name='diet',
            name='diet_type',
            field=models.CharField(default='balanced', help_text='Tipo de dieta (balanced, lowcarb, etc)', max_length=50),
        ),
        migrations.AddField(
            model_name='diet',
            name='gcdt',
            field=models.IntegerField(blank=True, help_text='Gasto Calórico Diário Total', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='goal',
            field=models.TextField(blank=True, help_text='Objetivo da dieta', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instruções e observações', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='target_calories',
            field=models.IntegerField(blank=True, help_text='Meta de calorias', null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='target_carbs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de carboidratos em gramas', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='target_fats',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de gorduras em gramas', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='target_protein',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de proteínas em gramas', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='tmb',
            field=models.IntegerField(blank=True, help_text='Taxa Metabólica Basal', null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='gcdt_calculado',
            field=models.PositiveIntegerField(blank=True, help_text='Gasto Calórico Diário Total calculado (legado)', null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='meals',
            field=models.JSONField(blank=True, null=True, validators=[diets.models.validate_meals_schema]),
        ),
        migrations.AlterField(
            model_name='diet',
            name='meta_calorias',
            field=models.PositiveIntegerField(blank=True, help_text='Meta de calorias diárias (legado)', null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='meta_carboidratos',
            field=models.PositiveIntegerField(blank=True, help_text='Meta de carboidratos em gramas (legado)', null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='meta_gorduras',
            field=models.PositiveIntegerField(blank=True, help_text='Meta de gorduras em gramas (legado)', null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='meta_proteinas',
            field=models.PositiveIntegerField(blank=True, help_text='Meta de proteínas em gramas (legado)', null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='tmb_calculado',
            field=models.PositiveIntegerField(blank=True, help_text='Taxa Metabólica Basal calculada (legado)', null=True),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da refeição (Café, Almoço, etc)', max_length=100)),
                ('time', models.TimeField(help_text='Horário da refeição')),
                ('day_of_week', models.IntegerField(default=0, help_text='Dia da semana (0=SEG, 1=TER, 2=QUA, 3=QUI, 4=SEX, 5=SAB, 6=DOM)')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição')),
                ('notes', models.TextField(blank=True, help_text='Orientações da refeição', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='diets.diet')),
            ],
            options={
                'verbose_name': 'Refeição',
                'verbose_name_plural': 'Refeições',
                'ordering': ['day_of_week', 'order', 'time'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='Nome do alimento', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantidade em unidade', max_digits=8)),
                ('unit', models.CharField(default='g', help_text='Unidade de medida (g, ml, und)', max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, help_text='Calorias calculadas', max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, help_text='Proteínas em g', max_digits=8)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carboidratos em g', max_digits=8)),
                ('fats', models.DecimalField(decimal_places=2, help_text='Gorduras em g', max_digits=8)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, help_text='Fibras em g', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taco_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_items', to='diets.alimentotaco')),
                ('tbca_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_items', to='diets.alimentotbca')),
                ('usda_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_items', to='diets.alimentousda')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diets.meal')),
            ],
            options={
                'verbose_name': 'Item Alimentar',
                'verbose_name_plural': 'Itens Alimentares',
                'ordering': ['meal', 'id'],
            },
        ),
    ]
