# Generated by Django 5.2.7 on 2026-01-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_defaultpreset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Arquivo PDF da dieta gerado', null=True, upload_to='diet_pdfs/%Y/%m/'),
        ),
    ]
