# Generated by Django 5.2.7 on 2026-01-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0009_diet_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpreset',
            name='diet_type',
            field=models.CharField(choices=[('normocalorica', 'Normocalórica'), ('balanced', 'Balanceado'), ('low_carb', 'Low Carb'), ('lowcarb', 'Low Carb (Legado)'), ('high_carb', 'High Carb'), ('highcarb', 'High Carb (Legado)'), ('cetogenica', 'Cetogênica'), ('ketogenic', 'Cetogênico (Legado)'), ('mediterranea', 'Mediterrânea'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('sem_gluten', 'Sem Glúten'), ('hiperproteica', 'Hiperproteica'), ('hypertrophy', 'Hipertrofia (Legado)'), ('weight_loss', 'Perda de Peso'), ('weight_gain', 'Ganho de Peso'), ('custom', 'Personalizado')], help_text='Tipo de dieta para este preset padrão', max_length=20),
        ),
        migrations.AlterField(
            model_name='defaultpreset',
            name='meal_type',
            field=models.CharField(choices=[('cafe_da_manha', 'Café da Manhã'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('lanche_manha', 'Lanche da Manhã'), ('lanche_tarde', 'Lanche da Tarde'), ('ceia', 'Ceia'), ('pre_treino', 'Pré-treino'), ('pos_treino', 'Pós-treino'), ('suplemento', 'Suplemento'), ('outros', 'Outros')], help_text='Tipo de refeição para este preset padrão', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealpreset',
            name='diet_type',
            field=models.CharField(choices=[('normocalorica', 'Normocalórica'), ('balanced', 'Balanceado'), ('low_carb', 'Low Carb'), ('lowcarb', 'Low Carb (Legado)'), ('high_carb', 'High Carb'), ('highcarb', 'High Carb (Legado)'), ('cetogenica', 'Cetogênica'), ('ketogenic', 'Cetogênico (Legado)'), ('mediterranea', 'Mediterrânea'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('sem_gluten', 'Sem Glúten'), ('hiperproteica', 'Hiperproteica'), ('hypertrophy', 'Hipertrofia (Legado)'), ('weight_loss', 'Perda de Peso'), ('weight_gain', 'Ganho de Peso'), ('custom', 'Personalizado')], default='balanced', help_text='Tipo de dieta para este preset', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealpreset',
            name='meal_type',
            field=models.CharField(choices=[('cafe_da_manha', 'Café da Manhã'), ('almoco', 'Almoço'), ('jantar', 'Jantar'), ('lanche_manha', 'Lanche da Manhã'), ('lanche_tarde', 'Lanche da Tarde'), ('ceia', 'Ceia'), ('pre_treino', 'Pré-treino'), ('pos_treino', 'Pós-treino'), ('suplemento', 'Suplemento'), ('outros', 'Outros')], help_text='Tipo de refeição para este preset', max_length=20),
        ),
    ]
