# Generated by Django 5.2.7 on 2026-01-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0010_alter_defaultpreset_diet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpreset',
            name='diet_type',
            field=models.CharField(choices=[('normocalorica', 'Normocalórica'), ('balanced', 'Balanceado'), ('low_carb', 'Low Carb'), ('lowcarb', 'Low Carb (Legado)'), ('high_carb', 'High Carb'), ('highcarb', 'High Carb (Legado)'), ('cetogenica', 'Cetogênica'), ('ketogenic', 'Cetogênico (Legado)'), ('mediterranea', 'Mediterrânea'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('sem_gluten', 'Sem Glúten'), ('hiperproteica', 'Hiperproteica'), ('hypertrophy', 'Hipertrofia (Legado)'), ('weight_loss', 'Perda de Peso'), ('weight_gain', 'Ganho de Peso'), ('custom', 'Personalizado'), ('personalizada', 'Personalizado (Frontend)')], help_text='Tipo de dieta para este preset padrão', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealpreset',
            name='diet_type',
            field=models.CharField(choices=[('normocalorica', 'Normocalórica'), ('balanced', 'Balanceado'), ('low_carb', 'Low Carb'), ('lowcarb', 'Low Carb (Legado)'), ('high_carb', 'High Carb'), ('highcarb', 'High Carb (Legado)'), ('cetogenica', 'Cetogênica'), ('ketogenic', 'Cetogênico (Legado)'), ('mediterranea', 'Mediterrânea'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('sem_gluten', 'Sem Glúten'), ('hiperproteica', 'Hiperproteica'), ('hypertrophy', 'Hipertrofia (Legado)'), ('weight_loss', 'Perda de Peso'), ('weight_gain', 'Ganho de Peso'), ('custom', 'Personalizado'), ('personalizada', 'Personalizado (Frontend)')], default='balanced', help_text='Tipo de dieta para este preset', max_length=20),
        ),
    ]
