# Generated by Django 5.2.7 on 2026-01-20 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0011_alter_defaultpreset_diet_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSubstitutionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_source', models.CharField(help_text='Fonte do alimento original (TACO, TBCA, USDA, IBGE)', max_length=20)),
                ('original_food_id', models.CharField(help_text='ID do alimento original na tabela de origem', max_length=100)),
                ('original_food_name', models.CharField(help_text='Nome do alimento original (cache para busca)', max_length=255)),
                ('substitute_source', models.CharField(help_text='Fonte do alimento substituto', max_length=20)),
                ('substitute_food_id', models.CharField(help_text='ID do alimento substituto na tabela de origem', max_length=100)),
                ('substitute_food_name', models.CharField(help_text='Nome do alimento substituto (cache para busca)', max_length=255)),
                ('diet_type', models.CharField(choices=[('normocalorica', 'Normocalórica'), ('low_carb', 'Low Carb'), ('high_carb', 'High Carb'), ('cetogenica', 'Cetogênica'), ('mediterranea', 'Mediterrânea'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('sem_gluten', 'Sem Glúten'), ('hiperproteica', 'Hiperproteica'), ('personalizada', 'Personalizada')], help_text='Tipo de dieta para esta substituição', max_length=20)),
                ('nutrient_predominant', models.CharField(choices=[('carb', 'Carboidrato'), ('protein', 'Proteína'), ('fat', 'Gordura')], help_text='Macronutriente predominante (carb, protein, fat)', max_length=10)),
                ('similarity_score', models.DecimalField(decimal_places=2, help_text='Similaridade nutricional (0.0 a 1.0)', max_digits=3)),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text='Multiplicador para ajustar quantidade baseada em macronutriente predominante', max_digits=10)),
                ('suggested_quantity', models.DecimalField(decimal_places=1, default=100, help_text='Quantidade padrão sugerida em gramas', max_digits=6)),
                ('priority', models.IntegerField(default=100, help_text='Prioridade de exibição (menor = mais prioritário)')),
                ('is_active', models.BooleanField(default=True, help_text='Se a regra está ativa')),
                ('notes', models.TextField(blank=True, help_text='Observações para o nutricionista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitution_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de Substituição',
                'verbose_name_plural': 'Regras de Substituição',
                'ordering': ['diet_type', 'priority', '-similarity_score'],
                'indexes': [models.Index(fields=['diet_type', 'nutrient_predominant'], name='diets_foods_diet_ty_47effd_idx'), models.Index(fields=['original_source', 'original_food_id'], name='diets_foods_origina_77c4cf_idx'), models.Index(fields=['is_active'], name='diets_foods_is_acti_f21102_idx')],
                'unique_together': {('original_source', 'original_food_id', 'substitute_source', 'substitute_food_id', 'diet_type')},
            },
        ),
        migrations.CreateModel(
            name='NutritionistSubstitutionFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_source', models.CharField(help_text='Fonte do alimento original', max_length=20)),
                ('original_food_id', models.CharField(help_text='ID do alimento original', max_length=100)),
                ('original_food_name', models.CharField(help_text='Nome do alimento original', max_length=255)),
                ('diet_type', models.CharField(choices=[('normocalorica', 'Normocalórica'), ('low_carb', 'Low Carb'), ('high_carb', 'High Carb'), ('cetogenica', 'Cetogênica'), ('mediterranea', 'Mediterrânea'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('sem_gluten', 'Sem Glúten'), ('hiperproteica', 'Hiperproteica'), ('personalizada', 'Personalizada')], help_text='Tipo de dieta para este favorito', max_length=20)),
                ('substitute_source', models.CharField(help_text='Fonte do alimento substituto', max_length=20)),
                ('substitute_food_id', models.CharField(help_text='ID do alimento substituto', max_length=100)),
                ('substitute_food_name', models.CharField(help_text='Nome do alimento substituto', max_length=255)),
                ('suggested_quantity', models.DecimalField(decimal_places=1, default=100, help_text='Quantidade padrão sugerida em gramas', max_digits=6)),
                ('similarity_score', models.DecimalField(decimal_places=2, default=0.8, help_text='Similaridade nutricional (0.0 a 1.0)', max_digits=3)),
                ('priority', models.IntegerField(default=10, help_text='Prioridade pessoal de exibição')),
                ('notes', models.TextField(blank=True, help_text='Notas pessoais do nutricionista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se o favorito está ativo')),
                ('nutritionist', models.ForeignKey(help_text='Nutricionista que favoritou', on_delete=django.db.models.deletion.CASCADE, related_name='substitution_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Substituição Favorita',
                'verbose_name_plural': 'Substituições Favoritas',
                'ordering': ['nutritionist', 'diet_type', 'priority'],
                'indexes': [models.Index(fields=['nutritionist', 'diet_type', 'original_food_id'], name='diets_nutri_nutriti_b86770_idx'), models.Index(fields=['is_active'], name='diets_nutri_is_acti_0bf8f2_idx')],
                'unique_together': {('nutritionist', 'original_source', 'original_food_id', 'diet_type', 'substitute_food_id')},
            },
        ),
    ]
