# Generated by Django 5.2.7 on 2026-01-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0014_food_substitution_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodsubstitution',
            options={'ordering': ['group', 'order', 'substitute_food_name'], 'verbose_name': 'Substituição de Alimento', 'verbose_name_plural': 'Substituições de Alimentos'},
        ),
        migrations.AlterModelOptions(
            name='foodsubstitutiongroup',
            options={'verbose_name': 'Grupo de Substituição', 'verbose_name_plural': 'Grupos de Substituição'},
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Se True, a substituição está aprovada para uso'),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordem de exibição na lista de substitutos'),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='original_food_id',
            field=models.CharField(help_text='ID do alimento original na fonte', max_length=100),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='original_food_name',
            field=models.CharField(help_text='Nome do alimento original para exibição', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='original_source',
            field=models.CharField(choices=[('TACO', 'Tabela TACO'), ('TBCA', 'Tabela TBCA'), ('USDA', 'USDA FoodData Central'), ('IBGE', 'IBGE POF')], help_text='Fonte do alimento original', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='substitute_calories_per_100g',
            field=models.FloatField(help_text='Calorias por 100g do substituto'),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='substitute_carbs_per_100g',
            field=models.FloatField(help_text='Carboidratos por 100g do substituto'),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='substitute_fat_per_100g',
            field=models.FloatField(help_text='Gorduras por 100g do substituto'),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='substitute_fiber_per_100g',
            field=models.FloatField(default=0, help_text='Fibra por 100g do substituto'),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='substitute_food_id',
            field=models.CharField(help_text='ID do alimento substituto na fonte', max_length=100),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='substitute_food_name',
            field=models.CharField(help_text='Nome do alimento substituto para exibição', max_length=255),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='substitute_protein_per_100g',
            field=models.FloatField(help_text='Proteína por 100g do substituto'),
        ),
        migrations.AlterField(
            model_name='foodsubstitution',
            name='substitute_source',
            field=models.CharField(choices=[('TACO', 'Tabela TACO'), ('TBCA', 'Tabela TBCA'), ('USDA', 'USDA FoodData Central'), ('IBGE', 'IBGE POF')], help_text='Fonte do alimento substituto', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodsubstitutiongroup',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição do grupo', null=True),
        ),
        migrations.AlterField(
            model_name='foodsubstitutiongroup',
            name='name',
            field=models.CharField(help_text='Nome do grupo de substituição (ex: Carboidratos Complexos)', max_length=100),
        ),
        migrations.AlterField(
            model_name='foodsubstitutiongroup',
            name='predominant_nutrient',
            field=models.CharField(choices=[('carbs', 'Carboidrato'), ('protein', 'Proteína'), ('fat', 'Gordura'), ('fiber', 'Fibra')], help_text='Macronutriente predominante para cálculo de equivalência', max_length=20),
        ),
    ]
