# Generated by Django 5.2.7 on 2026-01-25 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0015_alter_foodsubstitution_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do alimento personalizado', max_length=200)),
                ('grupo', models.CharField(blank=True, help_text='Grupo alimentar', max_length=100, null=True)),
                ('energia_kcal', models.FloatField(default=0, help_text='Energia em kcal por 100g')),
                ('proteina_g', models.FloatField(default=0, help_text='Proteína em gramas por 100g')),
                ('lipidios_g', models.FloatField(default=0, help_text='Lipídios em gramas por 100g')),
                ('carboidrato_g', models.FloatField(default=0, help_text='Carboidrato em gramas por 100g')),
                ('fibra_g', models.FloatField(default=0, help_text='Fibra em gramas por 100g')),
                ('unidade_caseira', models.CharField(blank=True, help_text='Ex: 1 Unidade, 1 Colher de sopa', max_length=100, null=True)),
                ('peso_unidade_caseira_g', models.FloatField(blank=True, help_text='Peso em gramas da unidade caseira', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutritionist', models.ForeignKey(help_text='Nutricionista proprietário do alimento', on_delete=django.db.models.deletion.CASCADE, related_name='custom_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alimento Personalizado',
                'verbose_name_plural': 'Alimentos Personalizados',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nutritionist', 'nome'], name='diets_custo_nutriti_40d581_idx')],
            },
        ),
    ]
