# Generated by Django 5.2.7 on 2025-12-16 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/', verbose_name='Logo do Consultório')),
                ('primary_color', models.CharField(default='#22c55e', help_text='Ex: #22c55e', max_length=7, verbose_name='Cor Primária (hex)')),
                ('secondary_color', models.CharField(default='#059669', help_text='Ex: #059669', max_length=7, verbose_name='Cor Secundária (hex)')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Nome Comercial')),
                ('crn_number', models.CharField(blank=True, max_length=50, verbose_name='Número do CRN')),
                ('professional_license', models.CharField(blank=True, max_length=100, verbose_name='Licença Profissional')),
                ('email_signature', models.TextField(blank=True, verbose_name='Assinatura de E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de Contato')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('document_header', models.TextField(blank=True, verbose_name='Cabeçalho de Documentos')),
                ('document_footer', models.TextField(blank=True, verbose_name='Rodapé de Documentos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to=settings.AUTH_USER_MODEL, verbose_name='Nutricionista')),
            ],
            options={
                'verbose_name': 'Branding do Usuário',
                'verbose_name_plural': 'Brandings dos Usuários',
                'ordering': ['user__name'],
            },
        ),
    ]
