# Generated by Django 5.2.7 on 2025-12-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbranding',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Imagem da assinatura (PNG/JPG). O fundo será removido automaticamente.', null=True, upload_to='branding/signatures/', verbose_name='Assinatura Digital'),
        ),
    ]
