# Generated by Django 5.2.7 on 2025-12-17 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_appointment_reminder', models.BooleanField(default=True, verbose_name='Notificar sobre lembretes de consulta')),
                ('notify_diet_expiry', models.BooleanField(default=True, verbose_name='Notificar sobre dietas próximas ao vencimento')),
                ('notify_new_message', models.BooleanField(default=True, verbose_name='Notificar sobre novas mensagens')),
                ('notify_system', models.BooleanField(default=True, verbose_name='Notificar sobre notícias do sistema')),
                ('notify_payment', models.BooleanField(default=True, verbose_name='Notificar sobre pagamentos')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Receber notificações por e-mail')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Receber notificações push')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='Receber notificações dentro do app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Notificação',
                'verbose_name_plural': 'Configurações de Notificação',
            },
        ),
    ]
