# Demonstração do funcionamento do envio de email

print("DEMONSTRAÇÃO: Envio de Email de Boas-Vindas")
print("===========================================")
print()
print("Quando um novo paciente é cadastrado no sistema, o seguinte processo ocorre:")
print()
print("1. O cadastro do paciente é realizado com sucesso")
print("2. O sistema gera automaticamente um email de boas-vindas")
print("3. O email contém um link seguro para definição de senha")
print("4. O email é enviado para o endereço do paciente")
print()
print("EXEMPLO DE EMAIL QUE SERÁ ENVIADO:")
print()
print("Assunto: Bem-vindx à sua jornada de transformação, [Nome do Paciente]!")
print()
print("Olá [Nome do Paciente],")
print()
print("Parabéns por dar o primeiro passo rumo à sua transformação e bem-estar!")
print("Estamos verdadeiramente felizes em tê-lo conosco nesta jornada.")
print()
print("Como nutricionista responsável pelo seu acompanhamento, tenho total")
print("confiança que juntos alcançaremos excelentes resultados. Seu compromisso")
print("com a saúde e o bem-estar é inspirador.")
print()
print("Para darmos continuidade ao seu processo, é importante que você defina")
print("sua senha de acesso ao nosso sistema. Isso garantirá sua privacidade e")
print("segurança, além de permitir que você acesse seus planos alimentares,")
print("evoluções e comuniquemos de forma eficaz.")
print()
print("Clique no link abaixo para definir sua senha e acessar sua conta:")
print()
print("[Link seguro para definição de senha]")
print()
print("Estamos ansiosos para acompanhar seu progresso e celebrar cada conquista")
print("ao longo do caminho. Conte comigo com entusiasmo e dedicação durante")
print("todo o processo!")
print()
print("Com confiança no seu sucesso,")
print("[Nome do Nutricionista]")
print()
print("---")
print("Esta é uma mensagem automática. Por favor, não responda diretamente a este e-mail.")
print()
print("FUNCIONALIDADES AFETADAS:")
print("- Envio de email de boas-vindas para novos pacientes")
print("- Link seguro para definição de senha")
print("- Recuperação de senha por email")
print("- Outros emails automatizados do sistema")
print()
print("Para que isso funcione, é essencial que as credenciais de email estejam")
print("corretamente configuradas no arquivo .env")