# Generated by Django 5.2.7 on 2025-11-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('method', models.CharField(blank=True, choices=[('ADIPOMETRO', 'Adipômetro'), ('BIOIMPEDANCIA', 'Bioimpedância'), ('FITA_METRICA', 'Fita Métrica (Método da Marinha)')], db_index=True, max_length=20, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Altura em metros (ex: 1.75)', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Peso em kg (ex: 70.5)', max_digits=5, null=True)),
                ('body_fat', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de gordura (ex: 22.5)', max_digits=4, null=True)),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, help_text='Massa muscular em kg (ex: 55.2)', max_digits=5, null=True)),
                ('body_measurements', models.JSONField(blank=True, help_text='Medidas corporais em JSON (circunferências, dobras cutâneas, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evaluation_photos/%Y/%m/%d/')),
                ('label', models.CharField(choices=[('FRENTE', 'Frente'), ('LADO', 'Lado'), ('COSTAS', 'Costas')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
