# Generated by Django 5.2.7 on 2025-12-23 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_evaluation_bmi'),
        ('patients', '0004_patientprofile_target_body_fat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='external_exams/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('PNG', 'PNG'), ('JPEG', 'JPEG')], max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_exams', to='patients.patientprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exame Externo',
                'verbose_name_plural': 'Exames Externos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
