# Generated by Django 5.2.7 on 2025-12-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duração da consulta em minutos', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link para reunião online (se for consulta online)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('faltou', 'Faltou')], default='agendada', help_text='Status da consulta', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', help_text='Tipo de consulta: presencial ou online', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
