# Generated by Django 5.2.7 on 2025-12-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_duration_appointment_meeting_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('primeira_vez', 'Primeira Vez'), ('retorno', 'Retorno'), ('em_grupo', 'Em Grupo'), ('pacote', 'Pacote'), ('permuta', 'Permuta'), ('pessoal', 'Pessoal'), ('antropometria', 'Antropometria'), ('amigo', 'Amigo'), ('encaixe', 'Encaixe'), ('teste', 'Teste')], default='presencial', help_text='Tipo de consulta: presencial ou online', max_length=20),
        ),
    ]
