# Generated by Django 5.2.7 on 2025-12-16 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0005_alter_appointment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255, unique=True, verbose_name='ID do Evento Google')),
                ('google_calendar_id', models.CharField(max_length=255, verbose_name='ID do Calendário Google')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Evento Google Calendar',
                'verbose_name_plural': 'Eventos Google Calendar',
                'db_table': 'google_calendar_event',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='OAuth 2.0 Access Token', verbose_name='Token de Acesso')),
                ('refresh_token', models.TextField(help_text='OAuth 2.0 Refresh Token', verbose_name='Token de Atualização')),
                ('token_expiry', models.DateTimeField(help_text='Data/hora em que o token expira', verbose_name='Expiração do Token')),
                ('google_user_id', models.CharField(max_length=255, unique=True, verbose_name='ID do Usuário Google')),
                ('google_email', models.EmailField(max_length=254, verbose_name='Email do Google')),
                ('google_display_name', models.CharField(max_length=255, verbose_name='Nome de Exibição no Google')),
                ('is_active', models.BooleanField(default=True, verbose_name='Integração Ativa')),
                ('default_calendar_id', models.CharField(default='primary', max_length=255, verbose_name='ID do Calendário Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_integration', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Integração Google Calendar',
                'verbose_name_plural': 'Integrações Google Calendar',
                'db_table': 'google_calendar_integration',
            },
        ),
    ]
