# Generated by Django 5.2.7 on 2025-11-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Exame')),
                ('date', models.DateField(verbose_name='Data do Exame')),
                ('attachment', models.FileField(upload_to='lab_exams/%Y/%m/%d/', verbose_name='Anexo do Exame')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exame Laboratorial',
                'verbose_name_plural': 'Exames Laboratoriais',
                'ordering': ['-date'],
            },
        ),
    ]
