# Generated by Django 5.2.7 on 2025-12-22 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_exams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labexam',
            name='attachment',
            field=models.FileField(upload_to='lab_exams/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Anexo do Exame'),
        ),
    ]
