# Generated by Django 5.2.7 on 2025-11-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labexam',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
