# Generated by Django 5.2.7 on 2025-12-06 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.patientprofile')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('idade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('sexo', models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=20)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('hora_acorda', models.TimeField(blank=True, null=True)),
                ('hora_dorme', models.TimeField(blank=True, null=True)),
                ('dificuldade_dormir', models.TextField(blank=True)),
                ('horario_treino', models.CharField(blank=True, max_length=100)),
                ('tempo_disponivel_treino', models.CharField(blank=True, max_length=100)),
                ('dias_treino_semana', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)])),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('peso_status', models.CharField(blank=True, choices=[('Aumentando', 'Aumentando'), ('Diminuindo', 'Diminuindo'), ('Estável', 'Estável')], max_length=20)),
                ('alimentos_restritos', models.TextField(blank=True)),
                ('ja_fez_dieta', models.BooleanField(default=False)),
                ('resultado_dieta', models.TextField(blank=True)),
                ('intestino', models.CharField(blank=True, choices=[('Preso', 'Preso'), ('Regular', 'Regular')], max_length=20)),
                ('dias_sem_banheiro', models.IntegerField(blank=True, null=True)),
                ('vezes_banheiro_dia', models.IntegerField(blank=True, null=True)),
                ('litros_agua_dia', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('vontade_doce', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('horarios_maior_apetite', models.TextField(blank=True)),
                ('preferencia_lanches', models.CharField(blank=True, choices=[('Doce', 'Doce'), ('Salgado', 'Salgado'), ('Doce e Salgado', 'Doce e Salgado')], max_length=50)),
                ('frutas_preferencia', models.TextField(blank=True)),
                ('doenca_familiar', models.TextField(blank=True, help_text='Histórico de doenças na família')),
                ('problema_saude', models.BooleanField(default=False)),
                ('problemas_saude_detalhes', models.TextField(blank=True)),
                ('problema_articular', models.TextField(blank=True)),
                ('uso_medicamentos', models.BooleanField(default=False)),
                ('medicamentos_detalhes', models.TextField(blank=True)),
                ('uso_cigarros', models.BooleanField(default=False)),
                ('intolerancia', models.BooleanField(default=False)),
                ('intolerancia_detalhes', models.TextField(blank=True)),
                ('uso_anticoncepcional', models.BooleanField(default=False)),
                ('termogenico_usado', models.TextField(blank=True)),
                ('uso_alcool', models.BooleanField(default=False)),
                ('alcool_frequencia', models.CharField(blank=True, max_length=100)),
                ('ja_usou_anabolizante', models.BooleanField(default=False)),
                ('anabolizante_problemas', models.TextField(blank=True)),
                ('pretende_usar_anabolizante', models.BooleanField(default=False)),
                ('objetivo', models.CharField(blank=True, choices=[('Emagrecimento', 'Emagrecimento'), ('Ganho de massa muscular', 'Ganho de massa muscular'), ('Ganho de peso', 'Ganho de peso'), ('Trincar o shape', 'Trincar o shape')], max_length=100)),
                ('compromisso_relatorios', models.BooleanField(default=False, help_text='Se compromete a enviar fotos e relatórios semanalmente?')),
                ('pescoco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('foto_frente', models.ImageField(blank=True, help_text='Foto de frente (👙/🩲)', null=True, upload_to='anamnesis_photos/')),
                ('foto_lado', models.ImageField(blank=True, help_text='Foto de lado (👙/🩲)', null=True, upload_to='anamnesis_photos/')),
                ('foto_costas', models.ImageField(blank=True, help_text='Foto de costas (👙/🩲)', null=True, upload_to='anamnesis_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-created_at'],
            },
        ),
    ]
