# Generated by Django 5.2.7 on 2025-11-11 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patients.patientprofile')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('medical_conditions', models.JSONField(blank=True, null=True)),
                ('food_preferences', models.JSONField(blank=True, null=True)),
                ('allergies', models.JSONField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
