# Generated by Django 6.0 on 2025-12-06 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0001_initial'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamnesisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo de Anamnese',
                'verbose_name_plural': 'Modelos de Anamnese',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnamnesisResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('filled_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis_responses', to='patients.patientprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='anamnesis.anamnesistemplate')),
            ],
            options={
                'verbose_name': 'Resposta de Anamnese',
                'verbose_name_plural': 'Respostas de Anamnese',
                'ordering': ['-filled_date'],
            },
        ),
    ]
