# Generated by Django 5.2.7 on 2025-11-25 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamnesis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Anamnese', 'verbose_name_plural': 'Anamneses'},
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='food_preferences',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='height',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='anamnesis',
            name='weight',
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='alcool_frequencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='alimentos_restritos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='anabolizante_problemas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='cintura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='compromisso_relatorios',
            field=models.BooleanField(default=False, help_text='Se compromete a enviar fotos e relatórios semanalmente?'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='dias_sem_banheiro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='dias_treino_semana',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='dificuldade_dormir',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='doenca_familiar',
            field=models.TextField(blank=True, help_text='Histórico de doenças na família'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='foto_costas',
            field=models.ImageField(blank=True, help_text='Foto de costas (👙/🩲)', null=True, upload_to='anamnesis_photos/'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='foto_frente',
            field=models.ImageField(blank=True, help_text='Foto de frente (👙/🩲)', null=True, upload_to='anamnesis_photos/'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='foto_lado',
            field=models.ImageField(blank=True, help_text='Foto de lado (👙/🩲)', null=True, upload_to='anamnesis_photos/'),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='frutas_preferencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='hora_acorda',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='hora_dorme',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='horario_treino',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='horarios_maior_apetite',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='idade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='intestino',
            field=models.CharField(blank=True, choices=[('Preso', 'Preso'), ('Regular', 'Regular')], max_length=20),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='intolerancia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='intolerancia_detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='ja_fez_dieta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='ja_usou_anabolizante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='litros_agua_dia',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='medicamentos_detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('Emagrecimento', 'Emagrecimento'), ('Ganho de massa muscular', 'Ganho de massa muscular'), ('Ganho de peso', 'Ganho de peso'), ('Trincar o shape', 'Trincar o shape')], max_length=100),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='pescoco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='peso_status',
            field=models.CharField(blank=True, choices=[('Aumentando', 'Aumentando'), ('Diminuindo', 'Diminuindo'), ('Estável', 'Estável')], max_length=20),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='preferencia_lanches',
            field=models.CharField(blank=True, choices=[('Doce', 'Doce'), ('Salgado', 'Salgado'), ('Doce e Salgado', 'Doce e Salgado')], max_length=50),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='pretende_usar_anabolizante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='problema_articular',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='problema_saude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='problemas_saude_detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='profissao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='quadril',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='resultado_dieta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=20),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='tempo_disponivel_treino',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='termogenico_usado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='uso_alcool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='uso_anticoncepcional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='uso_cigarros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='uso_medicamentos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='vezes_banheiro_dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='vontade_doce',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
