# Generated by Django 5.2.7 on 2025-12-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0002_anamnesistemplate_anamnesisresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='auto_saved_at',
            field=models.DateTimeField(blank=True, help_text='Última atualização via auto-save', null=True),
        ),
    ]
