# Generated by Django 5.2.7 on 2025-12-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0003_anamnesis_auto_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='target_body_fat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de percentual de gordura corporal', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Meta de peso em kg', max_digits=5, null=True),
        ),
    ]
