# Generated by Django 5.2.7 on 2026-01-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0004_anamnesis_target_body_fat_anamnesis_target_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='acorda_noite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesis',
            name='alergia_medicamento',
            field=models.TextField(blank=True, help_text='Intolerância ou alérgico a algum medicamento'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='compromisso_relatorios',
            field=models.BooleanField(default=False, help_text='Você se compromete a enviar fotos e relatórios conforme orientado pelo nutri?'),
        ),
        migrations.AlterField(
            model_name='anamnesis',
            name='dificuldade_dormir',
            field=models.BooleanField(default=False),
        ),
    ]
