# Generated by Django 5.2.7 on 2026-01-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0005_anamnesis_acorda_noite_anamnesis_alergia_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesis',
            name='dias_sem_banheiro',
            field=models.CharField(blank=True, choices=[('a cada 2 dias', 'a cada 2 dias'), ('a cada 3 dias', 'a cada 3 dias'), ('a cada 4 dias', 'a cada 4 dias'), ('a mais de 5 dias', 'a mais de 5 dias')], max_length=50, null=True),
        ),
    ]
