# Generated by Django 5.2.7 on 2026-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0006_alter_anamnesis_dias_sem_banheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesis',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('Emagrecimento', 'Emagrecimento'), ('Ganho de massa muscular', 'Ganho de massa muscular'), ('Ganho de peso', 'Ganho de peso'), ('Trincar o shape', 'Trincar o shape'), ('PERDA_PESO', 'Perda de peso'), ('GANHO_MUSCULAR', 'Ganho de massa muscular'), ('MANUTENCAO_PESO', 'Manutenção do peso'), ('PERFORMANCE_ESPORTIVA', 'Performance esportiva'), ('GESTACAO_LACTACAO', 'Gestação e lactação'), ('DOENCAS_CRONICAS', 'Manejo de doenças crônicas'), ('REABILITACAO_NUTRICIONAL', 'Reabilitação nutricional'), ('TRANSTORNOS_ALIMENTARES', 'Transtornos alimentares'), ('ALERGIAS_INTOLERANCIAS', 'Alergias e intolerâncias alimentares'), ('DISTURBIOS_GASTROINTESTINAIS', 'Distúrbios gastrointestinais'), ('CONDICOES_HORMONAIS', 'Condições hormonais'), ('NUTRICAO_FUNCIONAL', 'Nutrição funcional e integrativa'), ('SUPLEMENTACAO_ORIENTADA', 'Suplementação orientada'), ('SAUDE_IDOSO', 'Saúde do idoso'), ('PREVENCAO_DOENCAS', 'Prevenção de doenças')], max_length=100),
        ),
    ]
