# Generated by Django 5.2.7 on 2026-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0007_alter_anamnesis_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesis',
            name='altura_status',
            field=models.CharField(blank=True, choices=[('Aumentando', 'Aumentando'), ('Diminuindo', 'Diminuindo'), ('Estável', 'Estável')], default='Estável', max_length=20),
        ),
    ]
