# Generated by Django 5.2.7 on 2025-12-16 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('trigger', models.CharField(choices=[('appointment_confirmation', 'Confirmação de Agendamento'), ('appointment_reminder', 'Lembrete 24h'), ('birthday', 'Aniversário'), ('follow_up', 'Follow-up pós-consulta')], max_length=50, verbose_name='Gatilho')),
                ('content', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Automação',
                'verbose_name_plural': 'Templates de Automação',
                'ordering': ['-created_at'],
            },
        ),
    ]
