# Generated by Django 5.2.7 on 2025-12-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtemplate',
            name='delay_hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Atraso em Horas'),
        ),
    ]
