# Generated by Django 5.2.7 on 2025-12-10 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de Perfil')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema')),
                ('language', models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en-US', 'Inglês (EUA)')], default='pt-BR', max_length=5, verbose_name='Idioma')),
                ('notifications_email', models.BooleanField(default=True, verbose_name='Notificações por Email')),
                ('notifications_push', models.BooleanField(default=True, verbose_name='Notificações Push')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
