# Generated by Django 5.2.7 on 2025-12-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authenticationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notifications_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notifications_push',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme',
        ),
    ]
