# Generated by Django 5.2.7 on 2025-12-12 17:43

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en-US', 'Inglês (EUA)')], default='pt-BR', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_email',
            field=models.BooleanField(default=True, verbose_name='Notificações por Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_push',
            field=models.BooleanField(default=True, verbose_name='Notificações Push'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), users.models.validate_image_file], verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema'),
        ),
    ]
