# Generated by Django 5.2.7 on 2026-01-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_options_userprofile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='crn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
